### ISSUE TITLE
Does not build on my system (0.3.9 and previous versions)

### ISSUE THREAD

**Issue by fcourchesne** [alexcrichton/backtrace-rs#113]
Here is the output, this is Arch Linux x86_64. I have make, objcopy and ar installed.

> 
>    Compiling backtrace-sys v0.1.23 (file:///home/fc/Coding/Rust/backtrace-rs/backtrace-sys)
> error: failed to run custom build command for `backtrace-sys v0.1.23 (file:///home/fc/Coding/Rust/backtrace-rs/backtrace-sys)`
> process didn't exit successfully: `/home/fc/Coding/Rust/backtrace-rs/target/debug/build/backtrace-sys-6aa30102f5d7b22e/build-script-build` (exit code: 101)
> --- stdout
> TARGET = Some("x86_64-unknown-linux-gnu")
> OPT_LEVEL = Some("0")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CC_x86_64-unknown-linux-gnu = None
> CC_x86_64_unknown_linux_gnu = None
> HOST_CC = None
> CC = None
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CFLAGS_x86_64-unknown-linux-gnu = None
> CFLAGS_x86_64_unknown_linux_gnu = None
> HOST_CFLAGS = None
> CFLAGS = None
> DEBUG = Some("true")
> running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "src/libbacktrace" "-I" "/home/fc/Coding/Rust/backtrace-rs/target/debug/build/backtrace-sys-a16c89d099c4d370/out" "-fvisibility=hidden" "-DBACKTRACE_ELF_SIZE=64" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/home/fc/Coding/Rust/backtrace-rs/target/debug/build/backtrace-sys-a16c89d099c4d370/out/src/libbacktrace/alloc.o" "-c" "src/libbacktrace/alloc.c"
> exit code: 0
> TARGET = Some("x86_64-unknown-linux-gnu")
> OPT_LEVEL = Some("0")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CC_x86_64-unknown-linux-gnu = None
> CC_x86_64_unknown_linux_gnu = None
> HOST_CC = None
> CC = None
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CFLAGS_x86_64-unknown-linux-gnu = None
> CFLAGS_x86_64_unknown_linux_gnu = None
> HOST_CFLAGS = None
> CFLAGS = None
> DEBUG = Some("true")
> running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "src/libbacktrace" "-I" "/home/fc/Coding/Rust/backtrace-rs/target/debug/build/backtrace-sys-a16c89d099c4d370/out" "-fvisibility=hidden" "-DBACKTRACE_ELF_SIZE=64" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/home/fc/Coding/Rust/backtrace-rs/target/debug/build/backtrace-sys-a16c89d099c4d370/out/src/libbacktrace/dwarf.o" "-c" "src/libbacktrace/dwarf.c"
> exit code: 0
> TARGET = Some("x86_64-unknown-linux-gnu")
> OPT_LEVEL = Some("0")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CC_x86_64-unknown-linux-gnu = None
> CC_x86_64_unknown_linux_gnu = None
> HOST_CC = None
> CC = None
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CFLAGS_x86_64-unknown-linux-gnu = None
> CFLAGS_x86_64_unknown_linux_gnu = None
> HOST_CFLAGS = None
> CFLAGS = None
> DEBUG = Some("true")
> running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "src/libbacktrace" "-I" "/home/fc/Coding/Rust/backtrace-rs/target/debug/build/backtrace-sys-a16c89d099c4d370/out" "-fvisibility=hidden" "-DBACKTRACE_ELF_SIZE=64" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/home/fc/Coding/Rust/backtrace-rs/target/debug/build/backtrace-sys-a16c89d099c4d370/out/src/libbacktrace/fileline.o" "-c" "src/libbacktrace/fileline.c"
> cargo:warning=src/libbacktrace/fileline.c: In function ‘fileline_initialize’:
> cargo:warning=src/libbacktrace/fileline.c:106:14: warning: implicit declaration of function ‘getpid’; did you mean ‘fgetpos’? [-Wimplicit-function-declaration]
> cargo:warning=       (long) getpid ());
> cargo:warning=              ^~~~~~
> cargo:warning=              fgetpos
> exit code: 0
> TARGET = Some("x86_64-unknown-linux-gnu")
> OPT_LEVEL = Some("0")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CC_x86_64-unknown-linux-gnu = None
> CC_x86_64_unknown_linux_gnu = None
> HOST_CC = None
> CC = None
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CFLAGS_x86_64-unknown-linux-gnu = None
> CFLAGS_x86_64_unknown_linux_gnu = None
> HOST_CFLAGS = None
> CFLAGS = None
> DEBUG = Some("true")
> running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "src/libbacktrace" "-I" "/home/fc/Coding/Rust/backtrace-rs/target/debug/build/backtrace-sys-a16c89d099c4d370/out" "-fvisibility=hidden" "-DBACKTRACE_ELF_SIZE=64" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/home/fc/Coding/Rust/backtrace-rs/target/debug/build/backtrace-sys-a16c89d099c4d370/out/src/libbacktrace/posix.o" "-c" "src/libbacktrace/posix.c"
> cargo:warning=src/libbacktrace/posix.c: In function ‘__rbt_backtrace_open’:
> cargo:warning=src/libbacktrace/posix.c:67:16: warning: implicit declaration of function ‘open’; did you mean ‘fopen’? [-Wimplicit-function-declaration]
> cargo:warning=   descriptor = open (filename, (int) (O_RDONLY | O_BINARY | O_CLOEXEC));
> cargo:warning=                ^~~~
> cargo:warning=                fopen
> cargo:warning=src/libbacktrace/posix.c:67:39: error: ‘O_RDONLY’ undeclared (first use in this function)
> cargo:warning=   descriptor = open (filename, (int) (O_RDONLY | O_BINARY | O_CLOEXEC));
> cargo:warning=                                       ^~~~~~~~
> cargo:warning=src/libbacktrace/posix.c:67:39: note: each undeclared identifier is reported only once for each function it appears in
> cargo:warning=src/libbacktrace/posix.c: In function ‘__rbt_backtrace_close’:
> cargo:warning=src/libbacktrace/posix.c:94:7: warning: implicit declaration of function ‘close’; did you mean ‘fclose’? [-Wimplicit-function-declaration]
> cargo:warning=   if (close (descriptor) < 0)
> cargo:warning=       ^~~~~
> cargo:warning=       fclose
> exit code: 1
> 
> --- stderr
> thread 'main' panicked at '
> 
> Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "src/libbacktrace" "-I" "/home/fc/Coding/Rust/backtrace-rs/target/debug/build/backtrace-sys-a16c89d099c4d370/out" "-fvisibility=hidden" "-DBACKTRACE_ELF_SIZE=64" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/home/fc/Coding/Rust/backtrace-rs/target/debug/build/backtrace-sys-a16c89d099c4d370/out/src/libbacktrace/posix.o" "-c" "src/libbacktrace/posix.c" with args "cc" did not execute successfully (status code exit code: 1).
> 
> ', /home/fc/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.17/src/lib.rs:2180:5
> stack backtrace:
>    0:     0x56425a5f13fe - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h50a634a60cb4e5f7
>                                at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
>    1:     0x56425a5fc436 - std::sys_common::backtrace::print::hfdd27bb0425df770
>                                at libstd/sys_common/backtrace.rs:71
>                                at libstd/sys_common/backtrace.rs:59
>    2:     0x56425a5f4c8d - std::panicking::default_hook::{{closure}}::h027136eae47935d0
>                                at libstd/panicking.rs:211
>    3:     0x56425a5f4a00 - std::panicking::default_hook::hed5917d304f00a1b
>                                at libstd/panicking.rs:227
>    4:     0x56425a5f52fc - std::panicking::rust_panic_with_hook::hc482345e1eead25b
>                                at libstd/panicking.rs:511
>    5:     0x56425a5f50a9 - std::panicking::continue_panic_fmt::hc648628162a9da91
>                                at libstd/panicking.rs:426
>    6:     0x56425a5f500d - std::panicking::begin_panic_fmt::h300ed47d18028f56
>                                at libstd/panicking.rs:413
>    7:     0x56425a596531 - cc::fail::h0a7f34df048ead50
>                                at /home/fc/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.17/src/lib.rs:2180
>    8:     0x56425a5824be - cc::Build::compile::h4f5b2eff3aa3f0b8
>                                at /home/fc/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.17/src/lib.rs:913
>    9:     0x56425a57b28b - build_script_build::main::h38e6550738d19930
>                                at backtrace-sys/build.rs:92
>   10:     0x56425a57be9f - std::rt::lang_start::{{closure}}::h8bca9f114116c8e3
>                                at /checkout/src/libstd/rt.rs:74
>   11:     0x56425a5f4d92 - std::panicking::try::do_call::h7e0ed4dd1b773c21
>                                at libstd/rt.rs:59
>                                at libstd/panicking.rs:310
>   12:     0x56425a6077a9 - __rust_maybe_catch_panic
>                                at libpanic_unwind/lib.rs:105
>   13:     0x56425a5e1bd5 - std::rt::lang_start_internal::h7c38f1310577c409
>                                at libstd/panicking.rs:289
>                                at libstd/panic.rs:392
>                                at libstd/rt.rs:58
>   14:     0x56425a57be77 - std::rt::lang_start::h1bf0c925b683c653
>                                at /checkout/src/libstd/rt.rs:74
>   15:     0x56425a57b4ac - main
>   16:     0x7f4a6715c06a - __libc_start_main
>   17:     0x56425a578ab9 - _start
>   18:                0x0 - <unknown>
>

**Comment by alexcrichton** [comment]
It looks like the headers maybe a little different? If `close` isn't defined or `O_RDONLY` isn't defined that may mean that a different header should be included or something like that? Sorry without the ability to reproduce I'm not entirely sure :(

**Comment by fcourchesne** [comment]
I finally found out that avr-gcc was the culprit on my system (arch linux). Right after uninstalling it it works again.
