### ISSUE TITLE
Linux → Windows cross-compilation issue

### ISSUE THREAD

**Issue by fmorency** [alexcrichton/backtrace-rs#130]
I recently introduced the `vergen` crate in my project and the linux → windows cross-compilation (mingw) is now failing because of `backtrace-sys`.

The problem seems to reside in the fact that the `TARGET` environment variable is set to `x86_64-unknown-linux-gnu` when cross-compiling and doesn't contain the keyword `windows` that `backtrace-sys` expects from a windows computer.

Do you know if it's possible to cross-compile this crate?
Thanks!

**Comment by alexcrichton** [comment]
This crate should indeed be cross-compile-able! Do you perhaps need to set `CC_$target` instead of just a `CC` env var to configure the C compiler for just one target instead of all of them?

**Comment by fmorency** [comment]
Thanks for answering so fast! However, I'm not sure that I understand what you mean. Care to elaborate?

Here's some more information. The error is currently
```
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("x86_64-w64-mingw32-gcc")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
...
cargo:warning=src/libbacktrace/elf.c:43:18: fatal error: link.h: No such file or directory
cargo:warning= #include <link.h>
cargo:warning=                  ^
cargo:warning=compilation terminated.
exit code: 1
```

From what I understand (which is probably not that much), the `backtrace-sys` build file contains  things like
```
let target = env::var("TARGET").unwrap();

// libbacktrace isn't used on windows
if target.contains("windows") {
    return
}
```
but from the log above, it seems that `TARGET` is equal to `x86_64-unknown-linux-gnu` during the build and the windows-specific code is never executed. Does it make sense?

**Comment by alexcrichton** [comment]
Oh sure yeah, what's happening here is that `CC`, the environment variable you're using to specify the C compiler for the target, is *also* being used for the host. The `backtrace-sys` crate is common enough to get hooked up to both the host and the target frequently.

For example, your project may have a dependency on `backtrace-sys`. But one of your dependencies's build scripts may also depend on `backtrace-sys`. That means that Cargo compiles the `backtrace-sys` crate twice, once for the host and once for the target. The `CC` you've specified is only valid for the target (as you want the linux compiler for the host), but the `CC` env var blanket overrides everything.

If you configure, instead, `CC_x86_64-unknown-linux-gnu=...` though that should do the trick!

**Comment by fmorency** [comment]
Thanks for the clear explanation. I tried your fix and it worked perfectly! Thanks again.

**Comment by alexcrichton** [comment]
Ok great!
