### ISSUE TITLE
Does not compile with Rust 1.18

### ISSUE THREAD

**Issue by RalfJung** [alexcrichton/backtrace-rs#135]
The [failure crate](https://github.com/rust-lang-nursery/failure), which depends on this, supports Rust versions as far back as Rust 1.18.  This crate seems to only test on CI against current stable.  It is hence not entirely surprising that [backtrace currently fails to build against Rust 1.18](https://travis-ci.org/rust-lang-nursery/failure/jobs/466672292).

**Comment by RalfJung** [comment]
This could be resolved by bumping the minimal Rust version required by failure, or by fixing backtrace-rs -- but either way it seems the two crates should sync their CI in terms of which baseline Rust version they test.

**Comment by alexcrichton** [comment]
I'm not personally invested in making crates compile on such old versions of rustc, but I'm happy to merge PRs to fix compatibility!

**Comment by alexcrichton** [comment]
I'm gonna close this with #137 merged!
