### ISSUE TITLE
Build dependency autocfg triggers unexpected behavior

### ISSUE THREAD

**Issue by dianpopa** [alexcrichton/backtrace-rs#146]
Seems like the newly introduced `autocfg` build dependency introduces some new behavior when running unit tests. Apparently what it does is the binary associated to the project is run before any of the actual tests are run. This behavior was discovered when an [unit test](https://github.com/firecracker-microvm/firecracker/blob/master/src/main.rs#L199) failed due to resources left behind by `autocfg` trying to run the binary beforehand. Indeed from the official description, seems like `autocfg` tries to test code snippets to see if `rustc` will accept them. 
Consequently, any binary project that:
* creates resources,
* does not have a clean up tool integrated and 
* has unit tests that are expected to pass when run in a clean environment
is expected to encounter this problem.
Is this expected behavior? Is there any workaround to avoid using `autocfg` as a build dependency?

**Comment by alexcrichton** [comment]
Hm this sounds bad! I'm not sure though how it could be connected to that assertion? This crate only uses `autocfg` in the mode where it's looking at the rustc version as well, so I don't think it generates things. 

Do you have a build log to test out with though?

**Comment by dianpopa** [comment]
Hi,

Upon further investigation, we realized the issue was triggered by a combination of faulty logic inside our unit tests. 
For further details on what happened you can check out following [PR](https://github.com/firecracker-microvm/firecracker/pull/832).

Closing this per the above.
