### ISSUE TITLE
Backtrace fails to compile on 0.13.13 fails to compile with `--release --target=wasm32-unknown-unknown`

### ISSUE THREAD

**Issue by JD557** [alexcrichton/backtrace-rs#147]
I think that this is not a duplicate of #139 

`cargo web start --release --target=wasm32-unknown-unknown` fails with

```
LLVM ERROR: Function addresses with offsets not supported
error: Could not compile `backtrace`.
```

While `cargo web start --target=wasm32-unknown-unknown` seems to work just fine.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is a bug in LLVM used by rustc itself. This should be fixed on the beta branch of Rust though, and will be released shortly in January!
