### ISSUE TITLE
Cannot build-wasm the error-chain crate on rust stable, with backtrace failing to compile

### ISSUE THREAD

**Issue by cyplo** [alexcrichton/backtrace-rs#149]
Heya ! 

I have a project that transitively depends on `error-chaing` and I build it using `wasm-pack build --target nodejs` to produce a Node package. This fails on rust stable (1.31.1) but succeeds on rust beta (1.32.0-beta.12).

reproduction:
```
git clone https://github.com/rust-lang-nursery/error-chain.git
cat <<EOF >> Cargo.toml
[lib]
crate-type = ["cdylib", "rlib"]
EOF
rustup override set stable
wasm-pack build --target nodejs
[...]
LLVM ERROR: Function addresses with offsets not supported
error: Could not compile `backtrace`.
```
While changing `stable` to `beta` in the above steps makes the crate compile.
Not sure whether this will fix itself with Rust `beta` graduating to `stable` ?

**Comment by alexcrichton** [comment]
Thanks for the report! This looks the same as https://github.com/alexcrichton/backtrace-rs/issues/147 which should be fixed with the next Rust release as you've seen, so I think we'll wait and let that fix ride the trains!

**Comment by cyplo** [comment]
Thanks !

**Comment by cyplo** [comment]
Just to chime in here that compiling on `1.32 stable` works now - thanks a lot !
