### ISSUE TITLE
Cannot build v0.2.3 on beta/nightly

### ISSUE THREAD

**Issue by Mark-Simulacrum** [alexcrichton/backtrace-rs#155]
There appears to be some form of linker issue on beta and nightly but not stable, perhaps similar to https://github.com/alexcrichton/backtrace-rs/issues/24.

https://crater-reports.s3.amazonaws.com/beta-1.33-1/beta-2019-01-22/gh/drbawb.megumin/log.txt and quite a few other crates fail similarly in the latest crater run for the 1.33 beta.

Perhaps worth looking into but it is no longer the latest 'major' version of this crate (0.3 is the latest series).

**Comment by alexcrichton** [comment]
Thanks for the report! Looking into this it's actually a bug that was fixed long ago and the git repo here is pointing to a pretty ancient version of `backtrace-sys`. Updating both `backtrace-sys` and `libc` does the trick though!
