### ISSUE TITLE
Doesn't build in aarch64 (init_frame not working)

### ISSUE THREAD

**Issue by emilio** [alexcrichton/backtrace-rs#160]
I added some dependency that depends on backtrace transitively, and found out that this doesn't build in our windows aarch64 builders:

https://treeherder.mozilla.org/logviewer.html#/jobs?job_id=230326411&repo=autoland&lineNumber=12463

init_frame is of course not defined in `dbghelp.rs`. Can we make it so that it builds, shimming it or implementing it? I'm not quite sure about what that would entail.

**Comment by emilio** [comment]
cc @froydnj

**Comment by froydnj** [comment]
I think for shimming or implementing, we'd need a new `winapi-rs` release, so that we'd have definitions of all the necessary bits for aarch64.

**Comment by CryZe** [comment]
The new winapi version is out.
