### ISSUE TITLE
Stubs for WebAssembly

### ISSUE THREAD

**Issue by bjorn3** [alexcrichton/backtrace-rs#178]
This makes it easier to port crates using `backtrace-rs` to WASM.

cc rust-lang/miri#722

**Comment by alexcrichton** [comment]
I believe this should [already compile for wasm](https://github.com/alexcrichton/backtrace-rs/blob/319231374cd61018f06b8a514d445963eeb6fc6b/azure-pipelines.yml#L120-L130), but let me know if it's not working!

**Comment by bjorn3** [comment]
Oops, don't know why I though't it didn't work. :)
