### ISSUE TITLE
Adding ARM32 version of init_frame, but not sure how to set frame.AddrFrame.Offset

### ISSUE THREAD

**Issue by chandde** [alexcrichton/backtrace-rs#179]
Trying to add init_frame for arm32 in this file, https://github.com/alexcrichton/backtrace-rs/blob/master/src/backtrace/dbghelp.rs, I have CONTEXT/PCONTEXT defined here https://github.com/chandde/winapi-rs/blob/prtest3/src/um/winnt.rs#L1525, but I'm having trouble to identify the value for frame.AddrFrame.Offset. Any idea? It's a shame that MSDN doc does not even mention ARM or ARM64 for STACKFRAME64... https://docs.microsoft.com/en-us/windows/desktop/api/dbghelp/ns-dbghelp-stackframe64

**Comment by chandde** [comment]
Did more search online and it appears R11 is for frame pointer, close this issue. Please let me know if that's NOT the case.

**Comment by alexcrichton** [comment]
FWIW I've used [LLVM as a source of reference](https://github.com/llvm/llvm-project/blob/79b2828b3f8fb375a250394c0a70b20064f7e4c6/llvm/lib/Support/Windows/Signals.inc#L524-L550) for this in the past.

**Comment by chandde** [comment]
Thanks! Seems R11 is the right one, I guessed it right ☺

**Comment by chandde** [comment]
https://docs.microsoft.com/en-us/cpp/build/overview-of-arm-abi-conventions?view=vs-2019

This link also mentions r11 for frame pointer
