### ISSUE TITLE
Serialize backtrace

### ISSUE THREAD

**Issue by callicles** [alexcrichton/backtrace-rs#19]
Hi!

I am trying to serialize a Backtrace object like so:
```rust
fn serialize_backtrace(backtrace: &Backtrace) -> String {
    let backtrace_frames: Vec<BacktraceFrame> = backtrace.into();
    let to_print = backtrace_frames.into_iter()
        .map(|frame| frame.to_string() + "\n")
        .fold("", |acc, &frame_str| acc + frame_str);
}
```
It is telling me
```
the trait bound `std::vec::Vec<errors::backtrace::BacktraceFrame>: std::convert::From<&errors::backtrace::Backtrace>` is not satisfied
```

Although from the [doc:]( http://alexcrichton.com/backtrace-rs/backtrace/struct.Backtrace.html) I should be able to convert a backtrace in a vec of frames.

Also, 
```
the method `to_string` exists but the following trait bounds were not satisfied: `errors::backtrace::BacktraceFrame : std::fmt::Display`
```

I am confused since in the examples, the reference of backtrace is used in a `println!` statement.

Thanks for the help.

PS: I am on rust 1.13 on MacX 64 10.12.1 using backtrace 0.2 (same error with 0.3)

**Comment by alexcrichton** [comment]
If you're just looking for a "readable" version you can do `format!("{:?}", backtrace)`, but are you looking to deserialize it at some point?

**Comment by callicles** [comment]
No I am just looking to send the backtrace through ffi to a calling language. So that should do the trick. Thx!

**Comment by alexcrichton** [comment]
Ok! Closing in that case.
