### ISSUE TITLE
Handling of version hashes with symbol demangling

### ISSUE THREAD

**Issue by neon64** [alexcrichton/backtrace-rs#3]
rustc is producing symbol names like this: `_ZN2gl2Gl13CompileShader20h18931bbc7b159946zjfE`

when running it through `backtrace::demangle()` it returns the following `gl::Gl::CompileShader::h18931bbc7b159946zjf`. It it intentional that the `h18931bbc7b159946zjf` is still left on the end?

**Comment by alexcrichton** [comment]
Yeah this is currently intentional as it's part of the symbol name, it helps disambiguate functions between crates as the hash will be unique per crate.
