### ISSUE TITLE
SymbolName.as_str() returns the original mangled name

### ISSUE THREAD

**Issue by bkchr** [alexcrichton/backtrace-rs#36]
Hi, why does SymbolName.as_str() returns the mangled name and not the demangled name?
Because to get the demangled name, I need to call to_string(). Could we maybe change the interface? I could create a pull request. Or do you try to minimize the number of allocations?

**Comment by alexcrichton** [comment]
Could you instead write to a stack local buffer if you want to avoid allocations? In general there's not really a greaty way to provide the demangled version as the size isn't known ahead of time :(

**Comment by bkchr** [comment]
Yeah, that is hard to know the size in advance. Maybe you could just update the documentation? To make it more clear that it is not the demangled string? Because I tested my code on MacOS and there the "as_str()" function returned the demangled names, but on Linux that did not work :( Now, I am using the "to_string()" function, but to find this bug took a lot of time :D

**Comment by alexcrichton** [comment]
Makes sense to me!

**Comment by alexcrichton** [comment]
I believe this has been clarified in the docs now.
