### ISSUE TITLE
Error compiling for arm target (raspberry pi)

### ISSUE THREAD

**Issue by pentagolo** [alexcrichton/backtrace-rs#4]
This error occurres when i try to cross-compile for an arm-v6 taget with rust(082e47636 2015-08-03):

/home/frede/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.1.5/src/backtrace/libunwind.rs:158:29: 158:35 error: use of undeclared type name `c_uint`
/home/frede/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.1.5/src/backtrace/libunwind.rs:158         type _Unwind_Word = c_uint;
                                                                                                                                       ^~~~~~
<cfg_if macros>:1:1: 1:67 note: in expansion of __cfg_if_apply!
<cfg_if macros>:5:1: 6:79 note: expansion site
<cfg_if macros>:1:1: 7:74 note: in expansion of __cfg_if_items!
<cfg_if macros>:4:1: 6:29 note: expansion site
<cfg_if macros>:1:1: 6:31 note: in expansion of cfg_if!
/home/frede/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.1.5/src/backtrace/mod.rs:79:1: 93:2 note: expansion site
error: aborting due to previous error

**Comment by alexcrichton** [comment]
Thanks for the report!
