### ISSUE TITLE
bump kernel32-sys

### ISSUE THREAD

**Issue by luxvio** [alexcrichton/backtrace-rs#6]
Hi !
I've recently noticed that the `kernel32-sys` at 0.1 breaks the build of `glium` (inspecting the `Cargo.lock,` shows this is the only dependency that pulls 0.1) because of two crates linking to the same library.

I kinda cloned the repo, changed the version in `Cargo.toml` in a "brace yourselves" kinda fashion to see what breaks and what I would end up fixing, and it seems that bumping doesn't break building nor tests :smiley: 

Is is possible for the project to update the crate published at crates.io with newer kernel32/libc dependencies?  

Thanks for reading, hugs

**Comment by alexcrichton** [comment]
Done, thanks for the report!
