### ISSUE TITLE
Backtrace not displayed if invoked via ffi

### ISSUE THREAD

**Issue by lilith** [alexcrichton/backtrace-rs#63]
This is a regression from the default handler, which displays a full backtrace on linux, even if invoked from a ruby process.

```
stack backtrace:
   0:           0x4008a8 - <unknown>
   1:                0x0 - <unknown>
```

In this context, I'm invoking a Rust (C-compatible) API from Ruby. The current directory is not near the symbols, and the ruby is at `/home/n/.rvm/rubies/ruby-2.2.1/bin/ruby `

using backtrace 0.3.2, Rust nightly 2017-06-11

**Comment by alexcrichton** [comment]
Thanks for the report! This is on linux, right?

Have you tried twiddling the features of this crate to see which backtrace method works the best for this application? Sometimes some strategies work better than others, it's all sort of dependent on the context iirc.

**Comment by alexcrichton** [comment]
I'm going to close this since it may have been a local issue, but if it comes up again feel free to resubmit.
