### ISSUE TITLE
Getting a lot of <no info> blocks, Windows, rustc 1.19, stable-x86_64-pc-windows-gnu

### ISSUE THREAD

**Issue by orthecreedence** [alexcrichton/backtrace-rs#66]
Hello, thank you for the library (and sorry if this has already been asked...I did a search on google and the issues and didn't find anything).

I've just finished implementing error_chain in my app to get access to backtraces. However, when I'm (running with `RUST_BACKTRACE=1`) printing out the backtrace, I just get a bunch of `<no info>` blocks:

```rust
match my_app() {
    Ok(..) => {}
    Err(err) => { println!("{:?}", err.backtrace()); }
}
```

```
   0:           0xa95c23 - <no info>
   1:           0xa96688 - <no info>
   2:           0xa876b2 - <no info>
   3:           0xa87762 - <no info>
   4:           0x7be522 - <no info>
   5:           0x7bebf6 - <no info>
   6:           0x758349 - <no info>
   7:           0x7aa58e - <no info>
   8:           0x79932f - <no info>
   9:           0x7a42d7 - <no info>
  10:           0x7bc078 - <no info>
  11:           0x5187cb - <no info>
  12:           0x524f1d - <no info>
  13:           0x6a417b - <no info>
  14:           0x527244 - <no info>
  15:          0x112ef09 - <no info>
  16:           0x52578f - <no info>
  17:           0x521292 - <no info>
  18:           0x524873 - <no info>
  19:           0x606590 - <no info>
  20:          0x11299d0 - <no info>
  21:     0x7ff81ae12774 - BaseThreadInitThunk
```

I'm on Windows 10, x64, rustc 1.19.0, stable-x86_64-pc-windows-gnu. Am I doing something wrong?

**Comment by alexcrichton** [comment]
Have you compiled with debuginfo? I forget at this point if this is supposed to work on x86_64-pc-windows-gnu or not...

**Comment by orthecreedence** [comment]
I am not sure, actually. I'm using the rustc that came with rustup (stable), and I'm not seeing any options in rustc for listing the configure options. The best I could find was:

```bash
$ rustc --print cfg
debug_assertions
target_arch="x86_64"
target_endian="little"
target_env="gnu"
target_family="windows"
target_os="windows"
target_pointer_width="64"
windows
```

**Comment by alexcrichton** [comment]
Are you compiling the binary with the `--release` flag through Cargo?

**Comment by orthecreedence** [comment]
Oh, sorry I misunderstood. No I am not compiling with `--release`.

**Comment by alexcrichton** [comment]
Ah ok, thanks for the info. I think this is a case where the native Windows APIs are used right now which expect MSVC-style PDB information to desugar a backtrace. The MinGW targets need to use libbacktrace but this currently isn't implemented yet, so there's no info just yet :(

**Comment by orthecreedence** [comment]
Ok, not a problem! That explanation makes sense, thank you.

**Comment by alexcrichton** [comment]
I think this should be fixed on master now, so closing.
