### ISSUE TITLE
Use gimli's inlined functions 

### ISSUE THREAD

**Issue by fitzgen** [alexcrichton/backtrace-rs#67]
Follow up to https://github.com/alexcrichton/backtrace-rs/pull/65

Right now, we only symbolicate the innermost inlined frame for each address, but instead we should report every inlined frame within the physical frame.

Depends on https://github.com/gimli-rs/addr2line/issues/11

**Comment by philipc** [comment]
This was fixed in #87.

**Comment by alexcrichton** [comment]
Right, oops!
