### ISSUE TITLE
`backtrace-sys/build.rs` doesn't pass `ranlib` to `configure`

### ISSUE THREAD

**Issue by sdemos** [alexcrichton/backtrace-rs#68]
For `ar` and `cc`, the build script finds those tools and passes them to the configure script using environment variables (https://github.com/alexcrichton/backtrace-rs/blob/master/backtrace-sys/build.rs#L105). The `libbacktrace` build also uses `ranlib`, which isn't passed to configure. Ordinarily, this wouldn't be a problem, since the configure script has enough information to figure out which one you want most of the time, but when you are passing a compiler to the build script to use instead of the obvious one (like if you have wrapper scripts to work around https://github.com/rust-lang/cargo/issues/4456 like we do) then it chooses the wrong one.

It seems like the best solution is to get the right tool using `find_tool` and pass that to `configure` using the `RANLIB` environment variable (which fixed the problem for me), so that all of the tools used by the `libbacktrace` build are definitely part of the same toolchain. I can submit a pull request doing just that, but I wanted to get feedback to make sure that was the correct approach or if there was a better thing to do.

**Comment by alexcrichton** [comment]
A PR sounds great, thanks!
