### ISSUE TITLE
Cross compile fail in docker (dockcore-armv7)

### ISSUE THREAD

**Issue by noyez** [alexcrichton/backtrace-rs#73]
## Symptom
When cross compiling backtrace-sys where error-chain and diesel_codegen are required, the `./configure` command kicked off by build.rs fails. It appears that the wrong build target is being used. The logs seem to indicate that the target is `x86_64-unknown-linux-gnu` when `armv7-unknown-linux-gnueabihf` is passed into cargo. As such the wrong compiler flags are passed to `arm-linux-gnueabihf-gcc`. The error in config.log is the following

```
configure:2999: /usr/bin/arm-linux-gnueabihf-gcc -O0 -ffunction-sections -fdata-sections -fPIC -g -m64 -Wall -Wextra   conftest.c  >&5
arm-linux-gnueabihf-gcc: error: unrecognized command line option '-m64'
```
## Reproduce
I created a git repo with an example project to trigger the error. Its just a hello-world program with dependencies of diesel_codegen and error-chain. I'm not sure what is so special about the combination of the two. The process makes use of docker and the [dockcross](https://github.com/dockcross/dockcross) base images, specifically [linux-armv7](https://github.com/dockcross/dockcross/tree/master/linux-armv7).

To reproduce Docker is needed, then clone https://github.com/noyez/xcompile_test.

 - Build the docker image from the git repo root directory.
    `docker build -t noyez/dockcore-armv7 .`

 - Using the previously built docker image, start a docker container with a bash shell.
    `docker run -ti -v $PWD:/work noyez/dockcore-armv7 bash`

 - Build the project from within the container.
    `gosu root cargo build --target=armv7-unknown-linux-gnueabihf`

I get the following build error:
```
error: failed to run custom build command for `backtrace-sys v0.1.16`
   	process didn't exit successfully: `/work/target/debug/build/backtrace-sys-514698a0155fc278/build-script-build` (exit code: 101)
    --- stdout
    OPT_LEVEL = Some("0")
    TARGET = Some("x86_64-unknown-linux-gnu")
    HOST = Some("x86_64-unknown-linux-gnu")
    TARGET = Some("x86_64-unknown-linux-gnu")
    TARGET = Some("x86_64-unknown-linux-gnu")
    HOST = Some("x86_64-unknown-linux-gnu")
    CC_x86_64-unknown-linux-gnu = None
    CC_x86_64_unknown_linux_gnu = None
    HOST_CC = None
    CC = Some("/usr/bin/arm-linux-gnueabihf-gcc")
    TARGET = Some("x86_64-unknown-linux-gnu")
    HOST = Some("x86_64-unknown-linux-gnu")
    CFLAGS_x86_64-unknown-linux-gnu = None
    CFLAGS_x86_64_unknown_linux_gnu = None
    HOST_CFLAGS = None
    CFLAGS = None
    DEBUG = Some("true")
    running: "sh" "/opt/rust/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/src/libbacktrace/configure" "--with-pic" "--disable-multilib" "--disable-shared" "--disable-host-shared" "--host=x86_64-unknown-linux-gnu" "--build=x86_64-unknown-linux-gnu"
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking target system type... x86_64-unknown-linux-gnu
    checking for x86_64-unknown-linux-gnu-gcc... /usr/bin/arm-linux-gnueabihf-gcc
    checking for C compiler default output file name...

    --- stderr
    configure: error: in `/work/target/debug/build/backtrace-sys-c8a25c9ec23a59ad/out':
    configure: error: C compiler cannot create executables
    See `config.log' for more details.
    thread 'main' panicked at 'failed with: exit code: 77', /opt/rust/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/build.rs:176:8
    note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by alexcrichton** [comment]
It looks like `CC` is specfied but backtrace-rs is being compiled for the host, so it's using the wrong compiler. I think if you use `CC_armv7-unknown-linux-gnueabihf` it should solve the problem!

**Comment by noyez** [comment]
Thanks for the tip, i eventually got it working.

FYI for anyone reading this. i fixed this via,
```
    unset CC
    export CC_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-gcc
```
