### ISSUE TITLE
Missing library on Ubuntu 17.10

### ISSUE THREAD

**Issue by artemshein** [alexcrichton/backtrace-rs#88]
> $ cargo build                     
>    Compiling backtrace-sys v0.1.16
> error: could not find native static library `backtrace`, perhaps an -L flag is missing?
> 
> error: Could not compile `backtrace-sys`.
> $ uname -a
> Linux UBUNTU 4.13.0-25-generic #29-Ubuntu SMP Mon Jan 8 21:14:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 
> $ lsb_release -r
> Release:	17.10 
> $ rustc --version
> rustc 1.23.0 (766bd11c8 2018-01-01)
> $ cargo --version
> cargo 0.24.0 (45043115c 2017-12-05)

Is there a specific prerequisite?

**Comment by alexcrichton** [comment]
Thanks for the report! Could you gist the full build log from scratch?

**Comment by artemshein** [comment]
Actually, `cargo clean`, `cargo build` resolved my issue somehow. Thank you :-)

**Comment by ConcurrentMarxistGC** [comment]
My issue was also solved by cleaning and rebuilding, same error message from cargo but I'm on linux mint.

> $ uname -a
> Linux minty 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> $ rustc --version
> rustc 1.30.0-nightly (551244f05 2018-09-10)
> $ cargo --version
> cargo 1.30.0-nightly (2fb77a49b 2018-09-07)

**Comment by mitchtbaum** [comment]
thanks @artemshein 

I had this issue too on Ubuntu (GalliumOS), though I'm not 100% sure if it directly solved it, because I also did `rustup` and had an issue with `error: could not rename component directory from ...` so I also did `rm -rf ~/.rustup/tmp`
