### ISSUE TITLE
There should probably be backtrace::trace_simple without arguments

### ISSUE THREAD

**Issue by vi** [alexcrichton/backtrace-rs#9]
with a pre-defined handler, just to print backtrace to stderr like in case of panic (but without panic).

If this pulls in additional dependencies, it can be optional feature.

**Comment by alexcrichton** [comment]
Are you thinking of something [like the example](https://github.com/alexcrichton/backtrace-rs/blob/master/examples/backtrace.rs)?

**Comment by vi** [comment]
Probably yes (not tried running).

**Comment by alexcrichton** [comment]
I believe this is closed now as `Backtrace::new()` was made and it has a "reasonable" `Debug` impl

**Comment by vi** [comment]
Note: there argumentless `new`, but no `Default` impl. Each such case makes `#[derive(Default)]` sadder.

**Comment by alexcrichton** [comment]
Ah yeah having a `Default` impl would be fine, wanna send a PR?
