### ISSUE TITLE
Cross compiling for Android via macOS "error: C compiler cannot create executables"

### ISSUE THREAD

**Issue by chrisballinger** [alexcrichton/backtrace-rs#95]
Although there were some similar issues already, none of them seemed to cover cross compiling for Android NDK 16b via macOS.

1. The first issue is that you must add `arm-linux-androideabi-gcc` to your `PATH`.
2. The second issue is that there doesn't seem to be a way to pass `sysroot` to libbacktrace's configure script.

```bash
export ANDROID_NDK_HOME="/usr/local/share/android-ndk"
export PATH="$ANDROID_NDK_HOME/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin:$PATH"
export PATH="$ANDROID_NDK_HOME/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin:$PATH"
```

To reproduce, try the example project here:

https://github.com/raizlabs/rust-universal-template

```
$ cargo build --target armv7-linux-androideabi --verbose --features "java"
       Fresh cc v1.0.15
       Fresh cesu8 v1.1.0
       Fresh same-file v1.0.2
       Fresh cfg-if v0.1.2
       Fresh ascii v0.7.1
       Fresh rustc-demangle v0.1.7
       Fresh byteorder v1.2.2
       Fresh jni-sys v0.3.0
       Fresh libc v0.2.40
       Fresh walkdir v2.1.4
       Fresh log v0.4.1
       Fresh combine v2.5.2
       Fresh example-generic v0.1.0 (file:///Users/chrisbal/Documents/Beach/rust-universal-template/Source/Rust/generic)
   Compiling backtrace-sys v0.1.16
       Fresh log v0.3.9
     Running `/Users/chrisbal/Documents/Beach/rust-universal-template/target/debug/build/backtrace-sys-264bc95b9cd1565e/build-script-build`
error: failed to run custom build command for `backtrace-sys v0.1.16`
process didn't exit successfully: `/Users/chrisbal/Documents/Beach/rust-universal-template/target/debug/build/backtrace-sys-264bc95b9cd1565e/build-script-build` (exit code: 101)
--- stdout
OPT_LEVEL = Some("0")
TARGET = Some("armv7-linux-androideabi")
HOST = Some("x86_64-apple-darwin")
TARGET = Some("armv7-linux-androideabi")
TARGET = Some("armv7-linux-androideabi")
HOST = Some("x86_64-apple-darwin")
CC_armv7-linux-androideabi = None
CC_armv7_linux_androideabi = None
TARGET_CC = None
CC = None
TARGET = Some("armv7-linux-androideabi")
HOST = Some("x86_64-apple-darwin")
CFLAGS_armv7-linux-androideabi = None
CFLAGS_armv7_linux_androideabi = None
TARGET_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "sh" "/Users/chrisbal/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/src/libbacktrace/configure" "--with-pic" "--disable-multilib" "--disable-shared" "--disable-host-shared" "--host=armv7-linux-androideabi" "--build=x86_64-apple-darwin"
checking build system type... x86_64-apple-darwin
checking host system type... armv7-unknown-linux-androideabi
checking target system type... armv7-unknown-linux-androideabi
checking for armv7-linux-androideabi-gcc... arm-linux-androideabi-gcc
checking for C compiler default output file name... 

--- stderr
configure: error: in `/Users/chrisbal/Documents/Beach/rust-universal-template/target/armv7-linux-androideabi/debug/build/backtrace-sys-2920521344c21fd7/out':
configure: error: C compiler cannot create executables
See `config.log' for more details.
thread 'main' panicked at 'failed with: exit code: 77', /Users/chrisbal/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/build.rs:176:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Without setting PATH:

<details>
<pre>
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by package-unused configure version-unused, which was
generated by GNU Autoconf 2.64.  Invocation command line was

  $ /Users/chrisbal/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/src/libbacktrace/configure --with-pic --disable-multilib --disable-shared --disable-host-shared --host=armv7-linux-androideabi --build=x86_64-apple-darwin

## --------- ##

hostname = Chris-MBP.local
uname -m = x86_64
uname -r = 17.5.0
uname -s = Darwin
uname -v = Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64
Kernel configured for up to 8 processors.
4 processors are physically available.
8 processors are logically available.
Processor type: x86_64h (Intel x86-64h Haswell)
Processors active: 0 1 2 3 4 5 6 7
Primary memory available: 16.00 gigabytes
Default processor set: 522 tasks, 2047 threads, 8 processors
Load average: 6.32, Mach factor: 3.10
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /Users/chrisbal/.cargo/bin
PATH: /Users/chrisbal/.cargo/bin
PATH: /usr/local/bin
PATH: /usr/local/bin
PATH: /Users/chrisbal/.gem/ruby/2.5.1/bin
PATH: /Users/chrisbal/.rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/bin
PATH: /Users/chrisbal/.rubies/ruby-2.5.1/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /usr/local/bin

## ----------- ##

configure:2524: checking build system type
configure:2538: result: x86_64-apple-darwin
configure:2558: checking host system type
configure:2571: result: armv7-unknown-linux-androideabi
configure:2591: checking target system type
configure:2604: result: armv7-unknown-linux-androideabi
configure:2641: checking for armv7-linux-androideabi-gcc
configure:2668: result: arm-linux-androideabi-gcc
configure:2937: checking for C compiler version
configure:2946: arm-linux-androideabi-gcc --version >&5
/Users/chrisbal/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/src/libbacktrace/configure: line 2948: arm-linux-androideabi-gcc: command not found
configure:2957: $? = 127
configure:2946: arm-linux-androideabi-gcc -v >&5
/Users/chrisbal/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/src/libbacktrace/configure: line 2948: arm-linux-androideabi-gcc: command not found
configure:2957: $? = 127
configure:2946: arm-linux-androideabi-gcc -V >&5
/Users/chrisbal/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/src/libbacktrace/configure: line 2948: arm-linux-androideabi-gcc: command not found
configure:2957: $? = 127
configure:2946: arm-linux-androideabi-gcc -qversion >&5
/Users/chrisbal/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/src/libbacktrace/configure: line 2948: arm-linux-androideabi-gcc: command not found
configure:2957: $? = 127
configure:2977: checking for C compiler default output file name
configure:2999: arm-linux-androideabi-gcc -O0 -ffunction-sections -fdata-sections -fPIC -g -march=armv7-a -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -Wall -Wextra   conftest.c  >&5
/Users/chrisbal/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/src/libbacktrace/configure: line 3001: arm-linux-androideabi-gcc: command not found
configure:3003: $? = 127
configure:3040: result: 
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "package-unused"
| #define PACKAGE_TARNAME "libbacktrace"
| #define PACKAGE_VERSION "version-unused"
| #define PACKAGE_STRING "package-unused version-unused"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3046: error: in `/Users/chrisbal/Documents/Beach/rust-universal-template/target/armv7-linux-androideabi/debug/build/backtrace-sys-2920521344c21fd7/out':
configure:3050: error: C compiler cannot create executables
See `config.log' for more details.

## ---------------- ##

ac_cv_build=x86_64-apple-darwin
ac_cv_env_CC_set=set
ac_cv_env_CC_value=arm-linux-androideabi-gcc
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-O0 -ffunction-sections -fdata-sections -fPIC -g -march=armv7-a -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -Wall -Wextra'
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=set
ac_cv_env_build_alias_value=x86_64-apple-darwin
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=armv7-linux-androideabi
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=armv7-unknown-linux-androideabi
ac_cv_prog_CC=arm-linux-androideabi-gcc
ac_cv_target=armv7-unknown-linux-androideabi

## ----------------- ##

ACLOCAL=''
ALLOC_FILE=''
AMTAR=''
AR='ar'
AUTOCONF=''
AUTOHEADER=''
AUTOMAKE=''
AWK=''
BACKTRACE_FILE=''
BACKTRACE_SUPPORTED=''
BACKTRACE_SUPPORTS_DATA=''
BACKTRACE_SUPPORTS_THREADS=''
BACKTRACE_USES_MALLOC=''
CC='arm-linux-androideabi-gcc'
CFLAGS='-O0 -ffunction-sections -fdata-sections -fPIC -g -march=armv7-a -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -Wall -Wextra'
CPP=''
CPPFLAGS=''
CYGPATH_W=''
DEFS=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EGREP=''
EXEEXT=''
EXTRA_FLAGS=''
FGREP=''
FORMAT_FILE=''
GREP=''
INSTALL_DATA=''
INSTALL_PROGRAM=''
INSTALL_SCRIPT=''
INSTALL_STRIP_PROGRAM=''
LD=''
LDFLAGS=''
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
MAINT=''
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE=''
MAKEINFO=''
MKDIR_P=''
NATIVE_FALSE=''
NATIVE_TRUE=''
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE=''
PACKAGE_BUGREPORT=''
PACKAGE_NAME='package-unused'
PACKAGE_STRING='package-unused version-unused'
PACKAGE_TARNAME='libbacktrace'
PACKAGE_URL=''
PACKAGE_VERSION='version-unused'
PATH_SEPARATOR=':'
PIC_FLAG=''
RANLIB='ranlib'
SED=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
VERSION=''
VIEW_FILE=''
WARN_FLAGS=''
ac_ct_CC=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__isrc=''
am__leading_dot=''
am__tar=''
am__untar=''
bindir='${exec_prefix}/bin'
build='x86_64-apple-darwin'
build_alias='x86_64-apple-darwin'
build_cpu='x86_64'
build_os='darwin'
build_vendor='apple'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='armv7-unknown-linux-androideabi'
host_alias='armv7-linux-androideabi'
host_cpu='armv7'
host_os='linux-androideabi'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh=''
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
libtool_VERSION=''
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p=''
multi_basedir=''
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target='armv7-unknown-linux-androideabi'
target_alias='armv7-linux-androideabi'
target_cpu='armv7'
target_os='linux-androideabi'
target_vendor='unknown'

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "package-unused"
#define PACKAGE_TARNAME "libbacktrace"
#define PACKAGE_VERSION "version-unused"
#define PACKAGE_STRING "package-unused version-unused"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""

configure: exit 77
</pre>
</details>

After setting PATH:

<details>
<pre>
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by package-unused configure version-unused, which was
generated by GNU Autoconf 2.64.  Invocation command line was

  $ /Users/chrisbal/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.16/src/libbacktrace/configure --with-pic --disable-multilib --disable-shared --disable-host-shared --host=armv7-linux-androideabi --build=x86_64-apple-darwin

## --------- ##

hostname = Chris-MBP.local
uname -m = x86_64
uname -r = 17.5.0
uname -s = Darwin
uname -v = Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64
Kernel configured for up to 8 processors.
4 processors are physically available.
8 processors are logically available.
Processor type: x86_64h (Intel x86-64h Haswell)
Processors active: 0 1 2 3 4 5 6 7
Primary memory available: 16.00 gigabytes
Default processor set: 520 tasks, 2006 threads, 8 processors
Load average: 2.04, Mach factor: 5.94
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /Users/chrisbal/.cargo/bin
PATH: /usr/local/share/android-ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin
PATH: /usr/local/share/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin
PATH: /Users/chrisbal/.cargo/bin
PATH: /usr/local/bin
PATH: /usr/local/bin
PATH: /Users/chrisbal/.gem/ruby/2.5.1/bin
PATH: /Users/chrisbal/.rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/bin
PATH: /Users/chrisbal/.rubies/ruby-2.5.1/bin
PATH: /usr/local/share/android-ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-gcc
PATH: /usr/local/share/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/
PATH: /Users/chrisbal/.cargo/bin
PATH: /usr/local/bin
PATH: /usr/local/bin
PATH: /Users/chrisbal/.cargo/bin
PATH: /usr/local/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /usr/local/bin

## ----------- ##

configure:2524: checking build system type
configure:2538: result: x86_64-apple-darwin
configure:2558: checking host system type
configure:2571: result: armv7-unknown-linux-androideabi
configure:2591: checking target system type
configure:2604: result: armv7-unknown-linux-androideabi
configure:2641: checking for armv7-linux-androideabi-gcc
configure:2668: result: arm-linux-androideabi-gcc
configure:2937: checking for C compiler version
configure:2946: arm-linux-androideabi-gcc --version >&5
arm-linux-androideabi-gcc (GCC) 4.9.x 20150123 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2957: $? = 0
configure:2946: arm-linux-androideabi-gcc -v >&5
Using built-in specs.
COLLECT_GCC=arm-linux-androideabi-gcc
COLLECT_LTO_WRAPPER=/usr/local/Caskroom/android-ndk/16b/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../libexec/gcc/arm-linux-androideabi/4.9.x/lto-wrapper
Target: arm-linux-androideabi
Configured with: /Volumes/Android/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/configure --prefix=/tmp/b4566ac8ab7a8039eb0f097bbc2e31fa --target=arm-linux-androideabi --host=x86_64-apple-darwin --build=x86_64-apple-darwin --with-gnu-as --with-gnu-ld --enable-languages=c,c++ --with-gmp=/buildbot/tmp/build/toolchain/temp-install --with-mpfr=/buildbot/tmp/build/toolchain/temp-install --with-mpc=/buildbot/tmp/build/toolchain/temp-install --with-cloog=/buildbot/tmp/build/toolchain/temp-install --with-isl=/buildbot/tmp/build/toolchain/temp-install --with-ppl=/buildbot/tmp/build/toolchain/temp-install --disable-ppl-version-check --disable-cloog-version-check --disable-isl-version-check --enable-cloog-backend=isl --with-host-libstdcxx='-static-libgcc -lstdc++ -lm' --disable-libssp --enable-threads --disable-nls --disable-libmudflap --disable-libgomp --disable-libstdc__-v3 --disable-sjlj-exceptions --disable-shared --disable-tls --disable-libitm --with-float=soft --with-fpu=vfp --with-arch=armv5te --enable-target-optspace --enable-bionic-libs --enable-libatomic-ifuncs=no --enable-initfini-array --disable-nls --prefix=/tmp/b4566ac8ab7a8039eb0f097bbc2e31fa --with-sysroot=/tmp/b4566ac8ab7a8039eb0f097bbc2e31fa/sysroot --with-binutils-version=2.27 --with-mpfr-version=3.1.1 --with-mpc-version=1.0.1 --with-gmp-version=5.0.5 --with-gcc-version=4.9 --with-gdb-version=none --with-gxx-include-dir=/tmp/b4566ac8ab7a8039eb0f097bbc2e31fa/include/c++/4.9.x --with-bugurl=http://source.android.com/source/report-bugs.html --enable-languages=c,c++ --disable-bootstrap --enable-plugins --enable-libgomp --enable-gnu-indirect-function --disable-libsanitizer --enable-gold --enable-threads --enable-eh-frame-hdr-for-static --enable-graphite=yes --with-isl-version=0.11.1 --with-cloog-version=0.18.0 --with-arch=armv5te --program-transform-name='s&^&arm-linux-androideabi-&' --enable-gold=default
Thread model: posix
gcc version 4.9.x 20150123 (prerelease) (GCC) 
configure:2957: $? = 0
configure:2946: arm-linux-androideabi-gcc -V >&5
arm-linux-androideabi-gcc: error: unrecognized command line option '-V'
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
configure:2957: $? = 1
configure:2946: arm-linux-androideabi-gcc -qversion >&5
arm-linux-androideabi-gcc: error: unrecognized command line option '-qversion'
arm-linux-androideabi-gcc: fatal error: no input files
compilation terminated.
configure:2957: $? = 1
configure:2977: checking for C compiler default output file name
configure:2999: arm-linux-androideabi-gcc -O0 -ffunction-sections -fdata-sections -fPIC -g -march=armv7-a -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -Wall -Wextra   conftest.c  >&5
/usr/local/Caskroom/android-ndk/16b/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtbegin_dynamic.o: No such file or directory
/usr/local/Caskroom/android-ndk/16b/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot open crtend_android.o: No such file or directory
/usr/local/Caskroom/android-ndk/16b/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc
/usr/local/Caskroom/android-ndk/16b/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -ldl
collect2: error: ld returned 1 exit status
configure:3003: $? = 1
configure:3040: result: 
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "package-unused"
| #define PACKAGE_TARNAME "libbacktrace"
| #define PACKAGE_VERSION "version-unused"
| #define PACKAGE_STRING "package-unused version-unused"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3046: error: in `/Users/chrisbal/Documents/Beach/rust-universal-template/target/armv7-linux-androideabi/debug/build/backtrace-sys-2920521344c21fd7/out':
configure:3050: error: C compiler cannot create executables
See `config.log' for more details.

## ---------------- ##

ac_cv_build=x86_64-apple-darwin
ac_cv_env_CC_set=set
ac_cv_env_CC_value=arm-linux-androideabi-gcc
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-O0 -ffunction-sections -fdata-sections -fPIC -g -march=armv7-a -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -Wall -Wextra'
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=set
ac_cv_env_build_alias_value=x86_64-apple-darwin
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=armv7-linux-androideabi
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=armv7-unknown-linux-androideabi
ac_cv_prog_CC=arm-linux-androideabi-gcc
ac_cv_target=armv7-unknown-linux-androideabi

## ----------------- ##

ACLOCAL=''
ALLOC_FILE=''
AMTAR=''
AR='arm-linux-androideabi-ar'
AUTOCONF=''
AUTOHEADER=''
AUTOMAKE=''
AWK=''
BACKTRACE_FILE=''
BACKTRACE_SUPPORTED=''
BACKTRACE_SUPPORTS_DATA=''
BACKTRACE_SUPPORTS_THREADS=''
BACKTRACE_USES_MALLOC=''
CC='arm-linux-androideabi-gcc'
CFLAGS='-O0 -ffunction-sections -fdata-sections -fPIC -g -march=armv7-a -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -Wall -Wextra'
CPP=''
CPPFLAGS=''
CYGPATH_W=''
DEFS=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EGREP=''
EXEEXT=''
EXTRA_FLAGS=''
FGREP=''
FORMAT_FILE=''
GREP=''
INSTALL_DATA=''
INSTALL_PROGRAM=''
INSTALL_SCRIPT=''
INSTALL_STRIP_PROGRAM=''
LD=''
LDFLAGS=''
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
MAINT=''
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE=''
MAKEINFO=''
MKDIR_P=''
NATIVE_FALSE=''
NATIVE_TRUE=''
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE=''
PACKAGE_BUGREPORT=''
PACKAGE_NAME='package-unused'
PACKAGE_STRING='package-unused version-unused'
PACKAGE_TARNAME='libbacktrace'
PACKAGE_URL=''
PACKAGE_VERSION='version-unused'
PATH_SEPARATOR=':'
PIC_FLAG=''
RANLIB='arm-linux-androideabi-ranlib'
SED=''
SET_MAKE=''
SHELL='/bin/sh'
STRIP=''
VERSION=''
VIEW_FILE=''
WARN_FLAGS=''
ac_ct_CC=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__isrc=''
am__leading_dot=''
am__tar=''
am__untar=''
bindir='${exec_prefix}/bin'
build='x86_64-apple-darwin'
build_alias='x86_64-apple-darwin'
build_cpu='x86_64'
build_os='darwin'
build_vendor='apple'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='armv7-unknown-linux-androideabi'
host_alias='armv7-linux-androideabi'
host_cpu='armv7'
host_os='linux-androideabi'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh=''
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
libtool_VERSION=''
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p=''
multi_basedir=''
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target='armv7-unknown-linux-androideabi'
target_alias='armv7-linux-androideabi'
target_cpu='armv7'
target_os='linux-androideabi'
target_vendor='unknown'

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "package-unused"
#define PACKAGE_TARNAME "libbacktrace"
#define PACKAGE_VERSION "version-unused"
#define PACKAGE_STRING "package-unused version-unused"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""

configure: exit 77
</pre>
</details>

**Comment by alexcrichton** [comment]
ah yeah that looks like the errors here, I think that's a misconfigured local compiler?

**Comment by chrisballinger** [comment]
I was able to figure out a workaround by making a wrapper script and using standalone NDKs:

`.cargo/config`

```toml
[target.aarch64-linux-android]
ar = "aarch64-linux-android-ar"
linker = "aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "arm-linux-androideabi-ar"
linker = "arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "i686-linux-android-ar"
linker = "i686-linux-android-clang"

[target.x86_64-linux-android]
ar = "x86_64-linux-android-ar"
linker = "x86_64-linux-android-clang"
```  

`build-android.sh`

```bash
#!/usr/bin/env bash

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
NDK_DIR="$SCRIPT_DIR/NDK"

# Check for standalone NDK

if [ ! -d "$NDK_DIR" ]; then
    echo "Standalone NDK not found, running create-ndk-standalone.sh"
    sh "Scripts/create-ndk-standalone.sh"
fi

if [ ! -d "$NDK_DIR" ]; then
    echo "Error: Could not find standalone NDK"
    exit 1
fi

# Add clang/gcc binaries to PATH
PATH="$NDK_DIR/arm/bin:$PATH"
PATH="$NDK_DIR/arm64/bin:$PATH"
PATH="$NDK_DIR/x86/bin:$PATH"
PATH="$NDK_DIR/x86_64/bin:$PATH"

cd "$SCRIPT_DIR"
cargo build --target armv7-linux-androideabi --features "java" --release
cargo build --target aarch64-linux-android --features "java"  --release
cargo build --target i686-linux-android --features "java"  --release
cargo build --target x86_64-linux-android --features "java"  --release
```

https://github.com/Raizlabs/rust-universal-template/tree/b34a62f3267cbc6060d6033f12804875564da3fd
